services:
  neo4j-db:
    image: neo4j:5.22
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data_enqi:/data
      - ./docker/init_neo4j.cypher:/docker-entrypoint-initdb.d/init.cypher
    networks:
      - influencer-net

  app:
    build: .
    container_name: influencerlens-app
    depends_on:
      - neo4j-db
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_INIT=0
      - NEO4J_LABEL=Influencer
      - NEO4J_FT_INDEX=influencer_ft
      - NEO4J_VEC_INDEX=influencer_summary_vec
      - VEC_DIM=1024
      - VEC_SIM=cosine
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    volumes:
      - ./:/app
      - ./outputs:/app/outputs
    ports:
      - "8000:8000"
    networks:
      - influencer-net

networks:
  influencer-net:
    driver: bridge
